-- 인스타그램 메트릭 저장용 테이블 (선택 사항)
-- Supabase SQL Editor에서 실행하세요.

create table if not exists instagram_metrics (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  follower_count bigint,
  dimension text not null,
  dimension_type text not null,
  start_date date,
  end_date date,
  likes bigint default 0,
  comments bigint default 0,
  views bigint default 0,
  avg_7d_likes numeric default 0,
  avg_7d_comments numeric default 0,
  avg_7d_views numeric default 0,
  likes_dod numeric,
  likes_wow numeric,
  likes_yoy numeric,
  comments_dod numeric,
  comments_wow numeric,
  comments_yoy numeric,
  views_dod numeric,
  views_wow numeric,
  views_yoy numeric,
  updated_at timestamptz default now(),
  unique(profile_id, dimension, dimension_type)
);

create index if not exists idx_instagram_metrics_profile
  on instagram_metrics(profile_id);
create index if not exists idx_instagram_metrics_updated
  on instagram_metrics(updated_at);
